version: "3"

services:
  db:
    build: ./db/
    environment:
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    expose:
      - "${DB_PORT}"
    volumes:
      - "dumpsterdb:/var/lib/mysql/"
  api:
    build: ./api/
    ports:
      - "${API_PORT}:${API_PORT}"

volumes:
  dumpsterdb:
